# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - dev
  - homol
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - ${{ if eq(variables['build.SourceBranchName'], 'main') }}:
      - group: 'web-emq-main'
  - ${{ if eq(variables['build.SourceBranchName'], 'homol') }}:
      - group: 'web-emq-homol'
  - ${{ if eq(variables['build.SourceBranchName'], 'dev') }}:
      - group: 'web-emq-dev'

steps:
  - script: |
      echo VITE_EAPI_BFF_EMQ: $(VITE_EAPI_BFF_EMQ)

  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  # Run the yarn install
  - script: |
      yarn install
    displayName: Yarn install

  # Run the yarn build
  - script: |
      yarn build
    displayName: Yarn build
    env:
      VITE_EAPI_BFF_EMQ: $(VITE_EAPI_BFF_EMQ)

  - task: CopyFiles@2
    inputs:
      sourceFolder: 'dist'
      contents: '**/*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      cleanTargetFolder: true
    displayName: 'Copy dist'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.SourcesDirectory)/dist'
      publishLocation: 'Container'
      ArtifactName: 'www' # output artifact named www
